// Generates geometry.js from ../assets/nileaux-emblem.svg.
//   node NileauxConvergence/emblem/generate.mjs
//
// The compound path is split into its eight closed subpaths. For the stroke
// layer each subpath is re-sequenced so that it begins at its lowest node: the
// command list is rotated, nothing is moved, scaled, or simplified. The fill
// layer keeps the original path string untouched.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const svg = readFileSync(join(here, '../assets/nileaux-emblem.svg'), 'utf8');
const full = svg.match(/ d="([^"]+)"/)[1];
const subpaths = full.split(/(?=M )/).map((s) => s.trim()).filter(Boolean);
if (subpaths.length !== 8) throw new Error(`expected 8 subpaths, found ${subpaths.length}`);

// Names follow the order the subpaths appear in the file.
const NAMES = ['silhouette', 'starOuter', 'starInner', 'ribbonInner', 'crescentRightOuter', 'crescentRightInner', 'ribbonLeft', 'ribbonLower'];

const fmt = (n) => String(n);

function rotateToLowest(d) {
  const commands = [...d.matchAll(/([MCL])([^MCL]*)/g)].map((m) => ({ type: m[1], nums: m[2].match(/-?\d*\.?\d+/g).map(Number) }));
  if (commands[0].type !== 'M') throw new Error('subpath must start with M');
  const start = commands[0].nums;

  // Segments keep their command letter. A C command may chain several cubic
  // segments (six numbers each); an L is a straight segment (two numbers).
  const segments = commands.slice(1).flatMap((c) => {
    const size = c.type === 'C' ? 6 : c.type === 'L' ? 2 : 0;
    if (!size || c.nums.length % size !== 0) throw new Error(`unexpected command ${c.type}`);
    const out = [];
    for (let i = 0; i < c.nums.length; i += size) out.push({ type: c.type, nums: c.nums.slice(i, i + size) });
    return out;
  });
  const endOf = (seg) => seg.nums.slice(-2);
  const [lx, ly] = endOf(segments[segments.length - 1]);
  if (Math.abs(lx - start[0]) > 1e-6 || Math.abs(ly - start[1]) > 1e-6) throw new Error('subpath is not closed');

  // Node k is the endpoint of segment k. Rotate so the lowest node comes first.
  let lowest = 0;
  segments.forEach((seg, i) => {
    if (endOf(seg)[1] > endOf(segments[lowest])[1]) lowest = i;
  });
  const rotated = [...segments.slice(lowest + 1), ...segments.slice(0, lowest + 1)];
  const origin = endOf(segments[lowest]);
  return `M ${fmt(origin[0])} ${fmt(origin[1])} ` + rotated.map((seg) => `${seg.type} ${seg.nums.map(fmt).join(' ')}`).join(' ');
}

const named = Object.fromEntries(subpaths.map((d, i) => [NAMES[i], d]));
const stroke = Object.fromEntries(subpaths.map((d, i) => [NAMES[i], rotateToLowest(d)]));

const out = `// Generated by generate.mjs from ../assets/nileaux-emblem.svg (viewBox 0 0 1024 1024).
// The SVG is the source of truth. Nothing here is redrawn, moved, or simplified.
//
// FULL        the untouched compound path, used for the fill layer.
// SUBPATHS    the eight closed subpaths exactly as they appear in the file.
// STROKE      the same subpaths re-sequenced to start at their lowest node, so
//             a stroke can grow from the bottom of the mark upward.

export const VIEWBOX = '0 0 1024 1024';

export const FULL = ${JSON.stringify(full)};

export const SUBPATHS = {
${Object.entries(named).map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join('\n')}
};

export const STROKE = {
${Object.entries(stroke).map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join('\n')}
};

/** Formation order: river first, crescent, right crescent, star last. */
export const DRAW_ORDER = ['silhouette', 'ribbonLower', 'ribbonInner', 'ribbonLeft', 'crescentRightOuter', 'crescentRightInner', 'starOuter', 'starInner'];
`;

writeFileSync(join(here, 'geometry.js'), out);
console.log('geometry.js written');
for (const [k, v] of Object.entries(stroke)) console.log(k.padEnd(20), 'starts at', v.slice(2, 30));
